import Link from "next/link";
import { freerolls } from "@/lib/freeroll-data";
import { filterFreerolls } from "@/lib/freerolls";
import { FreerollCard } from "@/components/freeroll-card";
import { tourFamilies } from "@/lib/tour-catalog";
import { tourGuideHref } from "@/lib/tour-guide-data";
import { festivals } from "@/lib/guide-data";
import { pageMeta } from "@/lib/site";
import { statusOf } from "@/lib/guide-utils";
import { FestivalGrid, SectionTitle } from "@/components/guide-ui";
export const revalidate = 900;
export const metadata = pageMeta("Free poker tournament guides & live festivals", "Find poker freerolls, understand entry conditions and follow official sources. Explore live tournament festivals and plan your next poker trip.", "/");
export default function Home() {
 const listed=filterFreerolls(freerolls,{});
 const upcoming=festivals.filter(f=>["upcoming","ongoing"].includes(statusOf(f))).sort((a,b)=>a.startDate.localeCompare(b.startDate));
 return <main id="main"><section className="hero container fr-hero"><div className="hero-copy"><p className="eyebrow">THE INDEPENDENT POKER GUIDE</p><h1>Find a freeroll.<br/><em>Know the conditions.</em></h1><p className="hero-description">Free poker tournaments, with the details that matter: who can enter, what the prizes really are, and where to find the official information.</p><form action="/freerolls" className="hero-search"><label><span>FIND A FREE-ENTRY PROGRAM</span><input name="q" aria-label="Search freeroll guides" placeholder="PokerStars, 888poker, Atlanta…"/></label><button className="button" type="submit">Explore freerolls ↗</button></form><div className="fr-quick-links"><Link href="/freerolls?entry=no-deposit">No deposit confirmed ↗</Link><Link href="/freerolls?mode=online">Online programs ↗</Link><Link href="/freerolls?when=week">Published starts this week ↗</Link></div><p className="fr-hero-note">Initial coverage of {listed.length} verified program guides. Eligibility varies by account and region.</p></div><aside className="fr-hero-panel"><div className="fr-zero" aria-hidden="true">0<span>BUY-IN ≠ ZERO CONDITIONS</span></div><h2>Read the small print.<br/>Before you click.</h2><ul><li><span>01</span> Deposit & ticket requirements</li><li><span>02</span> Cash, playing credit or prizes</li><li><span>03</span> Official sources, clearly linked</li></ul><Link className="text-link" href="/freerolls">Compare the entry conditions ↗</Link></aside></section>
 <section className="container section fr-first-section"><SectionTitle number="01" eyebrow="FREE POKER TOURNAMENTS" title="Explore freeroll guides"><Link className="text-link" href="/freerolls">All freeroll guides ↗</Link></SectionTitle><div className="fr-grid">{listed.slice(0,4).map(f=><FreerollCard key={f.id} item={f}/>)}</div></section>
 <section className="fr-live-section"><div className="container section"><SectionTitle number="02" eyebrow="LIVE TOURNAMENTS & TRAVEL" title="Find your next festival"><Link className="text-link" href="/tournaments">Live tournament calendar ↗</Link></SectionTitle><p className="fr-section-intro">Compare major festivals, selected buy-ins and travel information. Find your next poker tournament. Plan the trip.</p><div className="fr-tour-links">{tourFamilies.filter(t=>t.featured).map(t=><Link key={t.id} href={tourGuideHref(t.id)||`/tournaments?brand=${t.id}`}>{t.label} ↗</Link>)}</div><FestivalGrid items={upcoming.slice(0,3)}/><div className="fr-live-actions"><Link className="button button-outline" href="/tournaments">Search {upcoming.length} ongoing & upcoming festivals ↗</Link><Link className="text-link" href="/destinations">Explore destinations ↗</Link></div></div></section>
 <section className="container section fr-explainer"><div><p className="eyebrow">SOURCES YOU CAN CHECK</p><h2>The overview here.<br/>The full details there.</h2><p>Each guide links to the official rules, announcement or calendar. Read the overview, then confirm the event with its organizer.</p><Link href="/about" className="text-link">How we verify information ↗</Link></div><div><p className="eyebrow">CLEAR ABOUT AVAILABILITY</p><h2>A useful starting point.</h2><p>We publish information we can verify. Programs with unknown individual start times stay separate from dated listings, and source checks show when a recheck is due.</p><Link href="/freerolls" className="text-link">Find a guide for your market ↗</Link></div></section></main>;
}
