import Link from "next/link";
import { freerolls } from "@/lib/freeroll-data";
import { filterFreerolls } from "@/lib/freerolls";
import { FreerollCard } from "@/components/freeroll-card";
import { tourFamilies } from "@/lib/tour-catalog";
import { tourGuideHref } from "@/lib/tour-guide-data";
import { festivals } from "@/lib/guide-data";
import { pageMeta } from "@/lib/site";
import { statusOf } from "@/lib/guide-utils";
import { FestivalGrid, SectionTitle } from "@/components/guide-ui";
export const revalidate = 900;
export const metadata = pageMeta("Free poker tournaments & freeroll guides", "Find free poker tournaments and compare freeroll entry rules, rewards and eligible regions. Explore live festivals, travel guides and official sources.", "/");
export default function Home() {
 const listed=filterFreerolls(freerolls,{});
 const upcoming=festivals.filter(f=>["upcoming","ongoing"].includes(statusOf(f))).sort((a,b)=>a.startDate.localeCompare(b.startDate));
 return <main id="main"><section className="hero container fr-hero"><div className="hero-copy"><p className="eyebrow">THE INDEPENDENT POKER GUIDE</p><h1>Free poker tournaments.<br/><em>Find your next freeroll.</em></h1><p className="hero-description">Compare online poker freerolls and live free-entry games. See who can enter, any deposit or ticket requirements, and the rewards—then open the organizer’s official information.</p><form action="/freerolls" className="hero-search"><label><span>SEARCH FREE POKER TOURNAMENTS</span><input name="q" aria-label="Search freeroll guides" placeholder="PokerStars, 888poker, Atlanta…"/></label><button className="button" type="submit">Find freeroll guides ↗</button></form><div className="fr-quick-links"><Link href="/freerolls?entry=no-deposit">No deposit confirmed ↗</Link><Link href="/freerolls?mode=online">Online programs ↗</Link><Link href="/freerolls?when=week">Published starts this week ↗</Link></div><p className="fr-hero-note">{listed.length} program guides in our current coverage. Each shows eligible regions, official sources and its last source check.</p></div><aside className="fr-hero-panel"><div className="fr-zero" aria-hidden="true">0<span>BUY-IN ≠ ZERO CONDITIONS</span></div><h2>Compare the details.<br/>Choose your next game.</h2><ul><li><span>01</span> Deposit & ticket requirements</li><li><span>02</span> Cash, tournament credit or tickets</li><li><span>03</span> Official sources, clearly linked</li></ul><Link className="text-link" href="/freerolls">Compare the entry conditions ↗</Link></aside></section>
 <section className="container section fr-first-section"><SectionTitle number="01" eyebrow="FREE POKER TOURNAMENTS" title="Explore freeroll guides"><Link className="text-link" href="/freerolls">All freeroll guides ↗</Link></SectionTitle><div className="fr-grid">{listed.slice(0,4).map(f=><FreerollCard key={f.id} item={f}/>)}</div></section>
 <section className="fr-live-section"><div className="container section"><SectionTitle number="02" eyebrow="LIVE TOURNAMENTS & TRAVEL" title="Live poker tournaments & travel"><Link className="text-link" href="/tournaments">Live tournament calendar ↗</Link></SectionTitle><p className="fr-section-intro">Find WSOP Circuit stops, WPT festivals and other major live poker tournaments. Compare dates and selected buy-ins, then plan hotels and transport with our destination guides.</p><div className="fr-tour-links">{tourFamilies.filter(t=>t.featured).map(t=><Link key={t.id} href={tourGuideHref(t.id)||`/tournaments?brand=${t.id}`}>{t.label} ↗</Link>)}</div><FestivalGrid items={upcoming.slice(0,3)}/><div className="fr-live-actions"><Link className="button button-outline" href="/tournaments">Search {upcoming.length} ongoing & upcoming festivals ↗</Link><Link className="text-link" href="/destinations">Explore destinations ↗</Link></div></div></section>
 <section className="container section fr-explainer"><div><p className="eyebrow">SOURCES YOU CAN CHECK</p><h2>What is a poker freeroll?</h2><p>A poker freeroll is a tournament with no entry buy-in. Some still require a ticket, a funded account or other qualifications. Our guides explain the entry route and link to the organizer’s rules.</p><Link href="/about" className="text-link">How we verify information ↗</Link></div><div><p className="eyebrow">CLEAR ABOUT AVAILABILITY</p><h2>Find a tournament you can enter.</h2><p>Start with your country and entry conditions. Check the reward and any published start date, then follow the official link to confirm availability. Recurring programs stay separate from confirmed dated starts.</p><Link href="/freerolls" className="text-link">Find a guide for your market ↗</Link></div></section></main>;
}
