"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import type { User } from "firebase/auth";
import { observeFirebaseUser, signInWithEmailCodeToken, signOutFirebaseUser } from "@/lib/firebase-client";
export function Account() {
 const [user,setUser]=useState<User|null>(null),[restoring,setRestoring]=useState(true),[email,setEmail]=useState(""),[sent,setSent]=useState(false),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[cooldown,setCooldown]=useState(0);
 useEffect(()=>observeFirebaseUser(u=>{setUser(u);setRestoring(false)}),[]);
 useEffect(()=>{if(!cooldown)return;const timer=setTimeout(()=>setCooldown(c=>Math.max(0,c-1)),1000);return()=>clearTimeout(timer)},[cooldown]);
 async function send(){setBusy(true);setMessage("");try{const r=await fetch("/api/auth/email-code/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const d=await r.json();if(!r.ok)throw Error(d.error||"Could not send a code. Try again.");setSent(true);setCode("");setCooldown(d.resendInSeconds||45);setMessage("A six-digit code is on its way. It expires in 10 minutes.");}catch(e){setMessage(e instanceof Error?e.message:"Please try again.")}finally{setBusy(false)}}
 async function verify(){setBusy(true);setMessage("");try{const r=await fetch("/api/auth/email-code/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code})});const d=await r.json();if(!r.ok)throw Error(d.error||"Could not verify the code.");if(!d.customToken)throw Error("Sign-in could not be completed. Request a new code.");await signInWithEmailCodeToken(d.customToken);setMessage("");}catch(e){setMessage(e instanceof Error?e.message:"Please try again.")}finally{setBusy(false)}}
 return <div className="account-wrap"><div className="account-panel"><p className="eyebrow">YOUR ALL IN ACCOUNT</p><h1>{user?"Welcome back.":"Sign in with email."}</h1>{restoring?<p role="status">Checking your session…</p>:user?<><p>You are signed in as</p><p className="account-email">{user.email}</p><p>Tournament information is open to everyone. Personal tracking features are not part of this version.</p><button className="button" style={{marginTop:24}} disabled={busy} onClick={async()=>{setBusy(true);try{await signOutFirebaseUser();setSent(false);setCode("");setMessage("")}catch{setMessage("Could not sign out. Please try again.")}finally{setBusy(false)}}}>Sign out</button></>:<><p>No password needed. We will send a verification code to your email.</p><form className="account-form" onSubmit={e=>{e.preventDefault();void(sent?verify():send())}}>{!sent?<label>Email address<input type="email" name="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" disabled={busy}/></label>:<><p>Enter the code sent to <strong>{email}</strong>.</p><label>Verification code<input type="text" name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} placeholder="000000" disabled={busy}/></label></>}<button className="button" type="submit" disabled={busy||(sent&&code.length!==6)}>{busy?"Please wait…":sent?"Verify & sign in":"Send verification code"}</button></form>{sent&&<div className="account-links"><button disabled={busy} onClick={()=>{setSent(false);setCode("");setMessage("")}}>Use a different email</button><button disabled={busy||cooldown>0} onClick={()=>void send()}>{cooldown>0?`Resend in ${cooldown}s`:"Resend code"}</button></div>}</>}{message&&<p className="account-feedback" role="status">{message}</p>}</div><p className="account-note">No sign-in required to <Link href="/tournaments">browse tournaments ↗</Link><br/><Link href="/privacy">Privacy</Link> · <Link href="/terms">Terms</Link></p></div>;
}
