import Link from "next/link";
import { SaveButton } from "@/components/save-button";
import { notFound } from "next/navigation";
import { festivals, festivalBySlug, destinationById, sourcesFor } from "@/lib/guide-data";
import { pageMeta, SITE_URL } from "@/lib/site";
import { dateRange, formatDate, isStale, mainEvent, money, nextEditionOf, serializeJsonLd, statusOf } from "@/lib/guide-utils";
import { Breadcrumbs, ExternalLink, SourceList, Status, TravelGuide } from "@/components/guide-ui";
import { FestivalLifecycleNotice, FestivalOfficialLinks } from "@/components/festival-lifecycle";
import { familyForSeries } from "@/lib/tour-catalog";
import { tourGuideHref } from "@/lib/tour-guide-data";
type Props={params:Promise<{slug:string}>};
export const revalidate=3600;
export async function generateMetadata({params}:Props){
  const f=festivalBySlug((await params).slug);if(!f)return {};
  const archived=statusOf(f)==="ended";
  return pageMeta(archived?`${f.name} — Past festival`:f.name,archived?`${f.name} has ended. Browse this edition's dates, buy-ins and venue information for reference, with original official sources.`:`${f.name}: dates, key buy-ins, venue, travel essentials and official registration links.`,`/tournaments/${f.slug}`);
}
export default async function FestivalPage({params}:Props){
  const f=festivalBySlug((await params).slug);if(!f)notFound();
  const d=destinationById(f.destinationId), main=mainEvent(f);
  const archived=statusOf(f)==="ended", stale=isStale(f);
  const primarySources=sourcesFor(f.sourceIds);
  const contentUpdated=[f.updatedAt,d.updatedAt].sort().at(-1)!;
  const family=familyForSeries(f.tour), guideHref=family&&tourGuideHref(family.id);
  return <main id="main" className="container page"><Breadcrumbs items={[{label:"Tournaments",href:"/tournaments"},...(guideHref?[{label:family!.label+" guide",href:guideHref}]:[]),{label:f.name}]}/>
  <FestivalLifecycleNotice festival={f} archived={archived} next={nextEditionOf(f,festivals)} previous={festivals.find(candidate=>candidate.id===f.previousEditionId)}/>
  <div className="detail-hero"><div><p className="eyebrow">{f.tour} / {d.country}</p><h1>{f.name}</h1><div className="detail-save"><SaveButton festivalId={f.id} name={f.name}/></div><p className="detail-intro">{f.description}</p><div className="detail-location"><span>⌖ {d.city}, {d.country}</span><Status festival={f}/></div></div><div className="hero-summary"><span className="eyebrow">AT A GLANCE</span><strong>{dateRange(f.startDate,f.endDate)}</strong><p>{f.venue.name}</p><div><span>MAIN EVENT BUY-IN</span><strong>{money(main?.buyIn)}</strong></div><a href="#official" className="button">{archived?"Official sources ↗":"Official entry points ↗"}</a></div></div>
  <div className="verification-bar"><span>Source checked <strong>{formatDate(f.checkedAt.slice(0,10),true)}</strong></span><span>Information updated {formatDate(contentUpdated.slice(0,10),true)}</span><span className={stale?"warning-text":""}>{archived?"Archived · not routinely rechecked":stale?"Recheck due":"Sources linked below"}</span></div>
  {f.reviewNote && <p className="notice"><strong>Source discrepancy:</strong> {f.reviewNote}</p>}
  {f.dateNote && <p className="notice">{f.dateNote}</p>}
  <nav className="anchor-nav" aria-label="On this page"><a href="#overview">Overview</a><a href="#buyins">Key buy-ins</a><a href="#travel">{archived?"Destination guide":"Plan the trip"}</a><a href="#official">Official links</a></nav>
  <section id="overview" className="section compact"><div className="section-heading"><div><p className="eyebrow">{archived?"01 / ABOUT THIS EDITION":"01 / KNOW BEFORE YOU GO"}</p><h2>The tournament, in context.</h2></div></div>
  <div className="overview-grid"><div className="info-panel"><h3>Venue & location</h3><p>{f.venue.name}</p><p className="muted">{f.venue.address || `${d.city}, ${d.country}. Check the official venue page for the exact arrival address.`}</p><ExternalLink href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(f.venue.name+" "+d.city)}`}>Open venue map</ExternalLink><p className="fine-print">Times published by the organizer use {f.timezone.replaceAll("_"," ")}.</p></div>
  <div className="info-panel"><h3>{archived?"Entry information for this edition":"Registration essentials"}</h3><p>{f.registration || (archived?"Entry requirements for this edition were not confirmed in our overview.":"Confirm eligibility, identification requirements, payment methods and registration cutoffs with the organizer before travelling.")}</p><p className="fine-print">{archived?"This edition has ended. These details do not establish eligibility or availability for another edition.":"This site does not accept entries or payments. Registration takes place through the organizer."}</p></div>
  <div className="info-panel"><h3>Planning your budget</h3><p>Keep tournament entries separate from accommodation, airport transfers and meals. Allow for additional entries only when the tournament rules permit them.</p><p className="fine-print">Listed buy-ins are in their original currencies. Unconfirmed fees and live hotel rates are not estimated.</p></div></div></section>
  <section id="buyins" className="section compact"><p className="eyebrow">{archived?"02 / THIS EDITION’S HIGHLIGHTS":"02 / A FEW WAYS TO PLAY"}</p><h2>Key buy-ins & event highlights</h2><p className="section-description">{archived?"Selected buy-ins recorded for this edition. The official sources below may now describe a later edition.":f.scheduleCoverage}</p>
  <div className="highlight-grid">{f.tournaments.map(t=><article key={t.id} className={`highlight-card ${t.category==="main"?"highlight-main":""}`}><span className="eyebrow">{t.category==="main"?"MAIN EVENT":t.category==="satellite"?"SATELLITE":"SIDE EVENT"} · {t.game}</span><h3>{t.name}</h3><strong className="highlight-price">{money(t.buyIn)}</strong><dl className="fact-list"><div><dt>Fee breakdown</dt><dd>{t.fee?money(t.fee)+" included in total":"Not confirmed"}</dd></div><div><dt>Guarantee</dt><dd>{t.guarantee?money(t.guarantee):"Not confirmed"}</dd></div>{t.sessions.length>0&&<div><dt>{t.endDate?"Dates":"Published starts"}</dt><dd>{t.endDate?dateRange(t.sessions[0].date,t.endDate):[...new Set(t.sessions.map(s=>formatDate(s.date)))].join(", ")}</dd></div>}<div><dt>Re-entry</dt><dd>{t.reentry||(archived?"Not confirmed":"Check official rules")}</dd></div>{t.lateRegistration&&<div><dt>Late registration</dt><dd>{t.lateRegistration}</dd></div>}{t.levels&&<div><dt>Level structure</dt><dd>{t.levels}</dd></div>}{t.startingStack&&<div><dt>Starting chips</dt><dd>{t.startingStack}</dd></div>}</dl></article>)}</div>
  {!f.tournaments.length&&<p className="notice">{archived?"Key buy-ins were not confirmed for this edition.":"Key buy-ins are still being verified. Follow the official schedule below."}</p>}<p className="fine-print">Highlights are a selection, not the full schedule. A guarantee is not the final prize pool. {archived?"These historical highlights do not describe current entry options.":"Check the official schedule for all flights, satellites and live changes."}</p></section>
  <section id="travel" className="section compact"><div className="section-heading"><div><p className="eyebrow">03 / BEYOND THE TABLE</p><h2>{archived?`Explore ${d.city}.`:`Plan your time in ${d.city}.`}</h2></div><Link className="text-link" href={`/destinations/${d.id}`}>Destination guide ↗</Link></div>{archived&&<p className="section-description">The destination guide below is maintained separately from this historical edition. Check current availability with each provider; festival-specific offers from this edition are no longer current.</p>}<TravelGuide destination={d}/></section>
  <FestivalOfficialLinks festival={f} archived={archived}/>
  <section className="section compact source-section"><div><h3>Sources & verification</h3><SourceList ids={f.sourceIds}/></div><div><h3>What changed</h3>{f.changes.slice().reverse().map((c,i)=><p key={i}><time>{formatDate(c.date.slice(0,10),true)}</time> — {c.text}</p>)}</div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:serializeJsonLd({"@context":"https://schema.org","@type":"Event",name:f.name,url:SITE_URL+"/tournaments/"+f.slug,description:f.description,startDate:f.startDate,endDate:f.endDate,eventStatus:"https://schema.org/"+(f.status==="cancelled"?"EventCancelled":f.status==="postponed"?"EventPostponed":"EventScheduled"),eventAttendanceMode:"https://schema.org/OfflineEventAttendanceMode",location:{"@type":"Place",name:f.venue.name,address:{"@type":"PostalAddress",addressLocality:d.city,addressCountry:d.countryCode,...(f.venue.address?{streetAddress:f.venue.address}:{})}},organizer:{"@type":"Organization",name:f.tour,url:primarySources[0]?.url}})}}/>
  </main>;
}
