import Link from "next/link";
import { notFound } from "next/navigation";
import { festivalBySlug, destinationById, sourcesFor } from "@/lib/guide-data";
import { pageMeta, SITE_URL } from "@/lib/site";
import { dateRange, formatDate, isStale, mainEvent, money, serializeJsonLd } from "@/lib/guide-utils";
import { Breadcrumbs, ExternalLink, SourceList, Status, TravelGuide } from "@/components/guide-ui";
type Props={params:Promise<{slug:string}>};
export const revalidate=3600;
export async function generateMetadata({params}:Props){const f=festivalBySlug((await params).slug);return f?pageMeta(f.name,`${f.name}: dates, key buy-ins, venue, travel essentials and official registration links.`,`/tournaments/${f.slug}`):{};}
export default async function FestivalPage({params}:Props){
  const f=festivalBySlug((await params).slug);if(!f)notFound();
  const d=destinationById(f.destinationId), main=mainEvent(f);
  const primarySources=sourcesFor(f.sourceIds);
  const contentUpdated=[f.updatedAt,d.updatedAt].sort().at(-1)!;
  return <main id="main" className="container page"><Breadcrumbs items={[{label:"Tournaments",href:"/tournaments"},{label:f.name}]}/>
  <div className="detail-hero"><div><p className="eyebrow">{f.tour} / {d.country}</p><h1>{f.name}</h1><p className="detail-intro">{f.description}</p><div className="detail-location"><span>⌖ {d.city}, {d.country}</span><Status festival={f}/></div></div><div className="hero-summary"><span className="eyebrow">AT A GLANCE</span><strong>{dateRange(f.startDate,f.endDate)}</strong><p>{f.venue.name}</p><div><span>MAIN EVENT BUY-IN</span><strong>{money(main?.buyIn)}</strong></div><a href="#official" className="button">Official entry points ↗</a></div></div>
  <div className="verification-bar"><span>Source checked <strong>{formatDate(f.checkedAt.slice(0,10),true)}</strong></span><span>Information updated {formatDate(contentUpdated.slice(0,10),true)}</span><span className={isStale(f)?"warning-text":""}>{isStale(f)?"Recheck due":"Sources linked below"}</span></div>
  {f.reviewNote && <p className="notice"><strong>Source discrepancy:</strong> {f.reviewNote}</p>}
  {f.dateNote && <p className="notice">{f.dateNote}</p>}
  <nav className="anchor-nav" aria-label="On this page"><a href="#overview">Overview</a><a href="#buyins">Key buy-ins</a><a href="#travel">Plan the trip</a><a href="#official">Official links</a></nav>
  <section id="overview" className="section compact"><div className="section-heading"><div><p className="eyebrow">01 / KNOW BEFORE YOU GO</p><h2>The tournament, in context.</h2></div></div>
  <div className="overview-grid"><div className="info-panel"><h3>Venue & location</h3><p>{f.venue.name}</p><p className="muted">{f.venue.address || `${d.city}, ${d.country}. Check the official venue page for the exact arrival address.`}</p><ExternalLink href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(f.venue.name+" "+d.city)}`}>Open venue map</ExternalLink><p className="fine-print">Times published by the organizer use {f.timezone.replaceAll("_"," ")}.</p></div>
  <div className="info-panel"><h3>Registration essentials</h3><p>{f.registration || "Confirm eligibility, identification requirements, payment methods and registration cutoffs with the organizer before travelling."}</p><p className="fine-print">This site does not accept entries or payments. Registration takes place through the organizer.</p></div>
  <div className="info-panel"><h3>Planning your budget</h3><p>Keep tournament entries separate from accommodation, airport transfers and meals. Allow for additional entries only when the tournament rules permit them.</p><p className="fine-print">Listed buy-ins are in their original currencies. Unconfirmed fees and live hotel rates are not estimated.</p></div></div></section>
  <section id="buyins" className="section compact"><p className="eyebrow">02 / A FEW WAYS TO PLAY</p><h2>Key buy-ins & event highlights</h2><p className="section-description">{f.scheduleCoverage}</p>
  <div className="highlight-grid">{f.tournaments.map(t=><article key={t.id} className={`highlight-card ${t.category==="main"?"highlight-main":""}`}><span className="eyebrow">{t.category==="main"?"MAIN EVENT":t.category==="satellite"?"SATELLITE":"SIDE EVENT"} · {t.game}</span><h3>{t.name}</h3><strong className="highlight-price">{money(t.buyIn)}</strong><dl className="fact-list"><div><dt>Fee breakdown</dt><dd>{t.fee?money(t.fee)+" included in total":"Not confirmed"}</dd></div><div><dt>Guarantee</dt><dd>{t.guarantee?money(t.guarantee):"Not confirmed"}</dd></div>{t.sessions.length>0&&<div><dt>{t.endDate?"Dates":"Published starts"}</dt><dd>{t.endDate?dateRange(t.sessions[0].date,t.endDate):[...new Set(t.sessions.map(s=>formatDate(s.date)))].join(", ")}</dd></div>}<div><dt>Re-entry</dt><dd>{t.reentry||"Check official rules"}</dd></div>{t.lateRegistration&&<div><dt>Late registration</dt><dd>{t.lateRegistration}</dd></div>}{t.levels&&<div><dt>Level structure</dt><dd>{t.levels}</dd></div>}{t.startingStack&&<div><dt>Starting chips</dt><dd>{t.startingStack}</dd></div>}</dl></article>)}</div>
  {!f.tournaments.length&&<p className="notice">Key buy-ins are still being verified. Follow the official schedule below.</p>}<p className="fine-print">Highlights are a selection, not the full schedule. A guarantee is not the final prize pool. Check the official schedule for all flights, satellites and live changes.</p></section>
  <section id="travel" className="section compact"><div className="section-heading"><div><p className="eyebrow">03 / BEYOND THE TABLE</p><h2>Plan your time in {d.city}.</h2></div><Link className="text-link" href={`/destinations/${d.id}`}>Destination guide ↗</Link></div><TravelGuide destination={d}/></section>
  <section id="official" className="official-section"><div><p className="eyebrow">04 / TAKE THE NEXT STEP</p><h2>Interested? Go straight<br />to the source.</h2><p>Get the complete schedule, current rules and available registration options from the organizer.</p></div><div className="official-links"><ExternalLink className="button" href={f.registrationUrl}>Official event & registration</ExternalLink><ExternalLink className="button button-outline" href={f.scheduleUrl}>Full official schedule</ExternalLink>{f.venue.url&&<ExternalLink className="text-link" href={f.venue.url}>Venue & visitor information</ExternalLink>}<small>External websites may offer their own apps or require an account. Our account is separate.</small></div></section>
  <section className="section compact source-section"><div><h3>Sources & verification</h3><SourceList ids={f.sourceIds}/></div><div><h3>What changed</h3>{f.changes.slice().reverse().map((c,i)=><p key={i}><time>{formatDate(c.date.slice(0,10),true)}</time> — {c.text}</p>)}</div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:serializeJsonLd({"@context":"https://schema.org","@type":"Event",name:f.name,url:SITE_URL+"/tournaments/"+f.slug,description:f.description,startDate:f.startDate,endDate:f.endDate,eventStatus:"https://schema.org/"+(f.status==="cancelled"?"EventCancelled":f.status==="postponed"?"EventPostponed":"EventScheduled"),eventAttendanceMode:"https://schema.org/OfflineEventAttendanceMode",location:{"@type":"Place",name:f.venue.name,address:{"@type":"PostalAddress",addressLocality:d.city,addressCountry:d.countryCode,...(f.venue.address?{streetAddress:f.venue.address}:{})}},organizer:{"@type":"Organization",name:f.tour,url:primarySources[0]?.url}})}}/>
  </main>;
}
